# Site settings
name: Alister Cordiner
description: "software developer"
url: "https://cordiner.net/"

github_username:  acordiner
linkedin_username: acordiner
stack_of_username: 393304
twitter_username: alistercordiner
email: alister@cordiner.net

avatar: yes
avatar_img_path: "imgs/profile.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
